name: Docs - Publish Dev to Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/java/**'
      - 'src/main/javadoc/**'
      - 'pom.xml'
  workflow_dispatch: {}

concurrency:
  group: "pages-dev"
  cancel-in-progress: true

jobs:
  deploy-dev-javadoc:
    name: Docs - Deploy Development Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Java Environment
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Generate Javadoc Documentation
        run: mvn -B -T 1C compile javadoc:javadoc

      - name: Locate Generated Documentation
        id: find_folder
        run: |
          FOLDER=$(find target -name "apidocs" -type d | head -n 1)
          echo "javadoc_path=$FOLDER" >> $GITHUB_OUTPUT

      - name: Apply SEO Enhancements
        run: |
          sed -i \
            -e '/<meta name="description"/d' \
            -e '/id="autogex-heading"/d' \
            -e '/<head>/a <meta name="robots" content="noindex, nofollow">\n<meta name="description" content="Autogex Development Documentation." />' \
            ${{ steps.find_folder.outputs.javadoc_path }}/index.html

          find ${{ steps.find_folder.outputs.javadoc_path }} -name "*.html" -exec \
            sed -i '/<head>/a <link rel="icon" type="image/svg+xml" href="/favicon.svg">' {} +

      - name: Optimize Documentation Assets
        run: |
          npm install -g --no-audit --no-fund --ignore-scripts clean-css-cli html-minifier
          cleancss -O3 -o ${{ steps.find_folder.outputs.javadoc_path }}/resource-files/custom-javadoc.css ${{ steps.find_folder.outputs.javadoc_path }}/resource-files/custom-javadoc.css
          find ${{ steps.find_folder.outputs.javadoc_path }} -name "*.html" -exec html-minifier --collapse-whitespace --conservative-collapse --remove-comments --minify-js true --minify-css true -o {} {} \;

      - name: Publish Development Documentation to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.find_folder.outputs.javadoc_path }}
          destination_dir: dev
          keep_files: true

  trigger-sitemap:
    name: Util - Trigger Sitemap Update
    needs: deploy-dev-javadoc
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Trigger Sitemap Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run docs-sitemap.yml --ref main