name: Publishes Documentation on GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-javadoc:
    name: Javadoc Build & Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: JDK 25 Set Up
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Javadoc HTML Generation
        run: mvn -B javadoc:javadoc

      - name: Find Javadoc Folder Automatically
        id: find_folder
        run: |
          FOLDER=$(find target -name "apidocs" -type d | head -n 1)
          echo "The actual folder is located at: $FOLDER"
          echo "javadoc_path=$FOLDER" >> $GITHUB_OUTPUT

      - name: GitHub Pages Config
        uses: actions/configure-pages@v6

      - name: Artifacts Uploading
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ steps.find_folder.outputs.javadoc_path }}

      - name: Deployment
        id: deployment
        uses: actions/deploy-pages@v5
