name: Publishes Dev Documentation on GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

concurrency:
  group: "pages-dev"
  cancel-in-progress: true

jobs:
  deploy-dev-javadoc:
    name: Javadoc Build & Deploy (Dev)
    runs-on: ubuntu-latest
    
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: JDK 25 Set Up
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Javadoc HTML Generation
        run: mvn -B javadoc:javadoc

      - name: Find Javadoc Folder Automatically
        id: find_folder
        run: |
          FOLDER=$(find target -name "apidocs" -type d | head -n 1)
          echo "javadoc_path=$FOLDER" >> $GITHUB_OUTPUT

      - name: Inject Meta Tags & SEO Fixes
        run: |
          sed -i '/<meta name="description"/d' ${{ steps.find_folder.outputs.javadoc_path }}/index.html
          sed -i '/id="autogex-heading"/d' ${{ steps.find_folder.outputs.javadoc_path }}/index.html
          
          sed -i '/<head>/a <meta name="robots" content="noindex, nofollow"> <meta name="description" content="Autogex Development Documentation." />' ${{ steps.find_folder.outputs.javadoc_path }}/index.html
          find ${{ steps.find_folder.outputs.javadoc_path }} -name "*.html" -exec sed -i '/<head>/a <link rel="icon" type="image/svg+xml" href="/favicon.svg">' {} +
          touch ${{ steps.find_folder.outputs.javadoc_path }}/.nojekyll

      - name: Minify Frontend Assets (JS, CSS, SVG)
        run: |
          npm install -g terser clean-css-cli svgo html-minifier
          terser ${{ steps.find_folder.outputs.javadoc_path }}/version-switcher.js -o ${{ steps.find_folder.outputs.javadoc_path }}/version-switcher.js -c -m
          cleancss -O3 -o ${{ steps.find_folder.outputs.javadoc_path }}/custom-javadoc.css ${{ steps.find_folder.outputs.javadoc_path }}/custom-javadoc.css
          svgo ${{ steps.find_folder.outputs.javadoc_path }}/logo.svg
          svgo ${{ steps.find_folder.outputs.javadoc_path }}/favicon.svg
          find ${{ steps.find_folder.outputs.javadoc_path }} -name "*.html" -exec html-minifier --collapse-whitespace --conservative-collapse --remove-comments --minify-js true --minify-css true -o {} {} \;

      - name: Deploy to GitHub Pages (dev folder)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.find_folder.outputs.javadoc_path }}
          destination_dir: dev
          keep_files: true

      - name: Trigger Sitemap Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run sitemap.yml --ref main
