name: Publishes Documentation on GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-javadoc:
    name: Javadoc Build & Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: JDK 25 Set Up
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Javadoc HTML Generation
        run: mvn -B javadoc:javadoc

      - name: Find Javadoc Folder Automatically
        id: find_folder
        run: |
          FOLDER=$(find target -name "apidocs" -type d | head -n 1)
          echo "The actual folder is located at: $FOLDER"
          echo "javadoc_path=$FOLDER" >> $GITHUB_OUTPUT

      - name: Inject Meta Tags & SEO Fixes
        run: |
          sed -i '/<meta name="description"/d' ${{ steps.find_folder.outputs.javadoc_path }}/index.html

          sed -i '/<head>/a \
          <meta name="description" content="Autogex: A powerful Java engine for processing Finite State Automata and Regular Expressions. Convert Regex to minimal DFA easily." />' \
          ${{ steps.find_folder.outputs.javadoc_path }}/index.html
          
          sed -i '/id="autogex-heading"/d' ${{ steps.find_folder.outputs.javadoc_path }}/index.html

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@6a56a20238e631d653600cf792c3596722b78259
        with:
          base-url-path: https://autogex.eu.org/
          path-to-root: ${{ steps.find_folder.outputs.javadoc_path }}
          additional-extensions: html

      - name: Copy SEO Files
        run: |
          cp src/main/javadoc/robots.txt ${{ steps.find_folder.outputs.javadoc_path }}/
          cp src/main/javadoc/8c8a09117f884afb9d9769c48698cf19.txt ${{ steps.find_folder.outputs.javadoc_path }}/

      - name: Notify IndexNow
        run: |
          curl -X POST "https://api.indexnow.org/indexnow" \
            -H "Content-Type: application/json; charset=utf-8" \
            -d '{
              "host": "autogex.eu.org",
              "key": "8c8a09117f884afb9d9769c48698cf19",
              "keyLocation": "https://autogex.eu.org/8c8a09117f884afb9d9769c48698cf19.txt",
              "urlList": [
                "https://autogex.eu.org/",
                "https://autogex.eu.org/sitemap.xml"
              ]
            }'

      - name: GitHub Pages Config
        uses: actions/configure-pages@v6

      - name: Artifacts Uploading
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ steps.find_folder.outputs.javadoc_path }}

      - name: Deployment
        id: deployment
        uses: actions/deploy-pages@v5
